version: '3.8'

services:
  # Miniproyecto 2: Twitter Sentiment Strategy
  sentiment-analyzer:
    build: ./miniproyecto2/microservicio1
    ports:
      - "8001:8000"
    container_name: twitter-sentiment-analyzer
    environment:
      - SERVICE_NAME=Twitter Sentiment Analyzer

  portfolio-manager:
    build: ./miniproyecto2/microservicio2
    ports:
      - "8002:8000"
    container_name: portfolio-manager
    environment:
      - SERVICE_NAME=Portfolio Manager
    depends_on:
      - sentiment-analyzer

  # Miniproyecto 3: Intraday Strategy Using GARCH Model
  garch-predictor:
    build: ./miniproyecto3/microservicio1
    ports:
      - "8003:8000"
    container_name: garch-volatility-predictor
    environment:
      - SERVICE_NAME=GARCH Volatility Predictor

  intraday-strategy:
    build: ./miniproyecto3/microservicio2
    ports:
      - "8004:8000"
    container_name: intraday-strategy-engine
    environment:
      - SERVICE_NAME=Intraday Strategy Engine
    depends_on:
      - garch-predictor

  # Ray Services - Distributed Processing
  ray-sentiment-analyzer:
    build: 
      context: ./ray_services
      dockerfile: sentiment_analyzer/Dockerfile
    ports:
      - "8005:8000"
    container_name: ray-sentiment-analyzer
    environment:
      - SERVICE_NAME=Ray Sentiment Analyzer
      - RAY_ADDRESS=auto
    volumes:
      - ./ray_services/data:/app/data

  ray-portfolio-manager:
    build: 
      context: ./ray_services
      dockerfile: portfolio_manager/Dockerfile
    ports:
      - "8006:8000"
    container_name: ray-portfolio-manager
    environment:
      - SERVICE_NAME=Ray Portfolio Manager
      - RAY_ADDRESS=auto
    depends_on:
      - ray-sentiment-analyzer

  ray-garch-predictor:
    build: 
      context: ./ray_services
      dockerfile: garch_predictor/Dockerfile
    ports:
      - "8007:8000"
    container_name: ray-garch-predictor
    environment:
      - SERVICE_NAME=Ray GARCH Predictor
      - RAY_ADDRESS=auto
    volumes:
      - ./ray_services/data:/app/data

  ray-intraday-strategy:
    build: 
      context: ./ray_services
      dockerfile: intraday_strategy/Dockerfile
    ports:
      - "8008:8000"
    container_name: ray-intraday-strategy
    environment:
      - SERVICE_NAME=Ray Intraday Strategy
      - RAY_ADDRESS=auto
    volumes:
      - ./ray_services/data:/app/data
    depends_on:
      - ray-garch-predictor

networks:
  default:
    name: unified-services-network
